version: "3.4"
services:
  netbox:
    build: .
    container_name: netbox
    restart: unless-stopped
    depends_on:
      - netbox-cache
      - netbox-db
    links:
      - netbox-db:netbox-db
      - netbox-cache:netbox-cache
    env_file:
      - ./netbox.env
    
    volumes:
      - ./reports:/app/netbox/netbox/reports
      - ./scripts:/app/netbox/scripts
      - netbox-media-files:/app/netbox/netbox/media
    healthcheck:
      start_period: 60s
      timeout: 3s
      interval: 15s
      test: "curl -f http://localhost:8080/api/ || exit 1"
    ports:
      - 8001:8000
  
  netbox-cache:
    container_name: netbox-cache
    image: redis:6.2.6
    restart: unless-stopped
    env_file:
      - ./redis.env
    command:
      - /usr/local/etc/redis/redis.conf
    volumes:
      - ./netbox-cache/conf:/usr/local/etc/redis
      - netbox-redis-data:/app/netbox-redis-data

  netbox-db:
    container_name: netbox-db
    image: postgres:15.0-alpine
    restart: unless-stopped
    env_file:
      - ./postgres.env
    volumes:
      - netbox-postgres-data:/var/lib/postgresql/data

volumes:
  netbox-media-files:
    driver: local
  netbox-postgres-data:
    driver: local
  netbox-redis-data:
    driver: local
